# Silaty
# Copyright (c) 2018 - 2021 AXeL
# Copyright (c) 2014 - 2015 Jessewb786

language = 'English'

def set_language(lang):
	global language
	language = lang

def translate_text(text):
	#print ("DEBUG: translate text '%s' in '%s'" % (text, language))
	arabicTranslations = {
		'Silaty': 'صلاتي',
		'Fajr': 'الفجر',
		'Shuruk': 'الشروق',
		'Dhuhr': 'الظهر',
		'Asr': 'العصر',
		'Maghrib': 'المغرب',
		'Isha': 'العشاء',
		'System': 'إعدادات التطبيق',
		'Start Minimized:': 'إخفاء نافذة التطبيق عند بدء التشغيل:',
		'Daylight Saving Time:': 'تفعيل التوقيت الصيفي:',
		'Clock Format:': 'تنسيق الوقت:',
		'12h': '12 ساعة',
		'24h': '24 ساعة',
		'Adjust Hijri Calendar:': 'ضبط التقويم الهجري:',
		'Language:': 'اللغة:',
		'English': 'الإنجليزية',
		'French': 'الفرنسية',
		'Arabic': 'العربية',
		'Notifications': 'الإشعارات',
		'Show Time left with Icon:': 'عرض الوقت المتبقي بجانب الأيقونة:',
		'Enable audio notifications:': 'تفعيل الإشعارات الصوتية:',
		'Time before notification:': 'الوقت قبل الإشعار:',
		'Fajr Adhan:': 'أذان الفجر:',
		'Normal Adhan:': 'أذان عادي:',
		'Jurisprudence': 'الفقه',
		'Calculation Method:': 'طريقة الحساب:',
		'Makkah': 'مكة المكرمة',
		'Egypt': 'مصر',
		'Karachi': 'كراتشي',
		'ISNA': 'الجمعية الإسلامية لأمريكا الشمالية',
		'MWL': 'رابطة العالم الإسلامي',
		'Madhab:': 'المذهب:',
		'Hanafi': 'حنفي',
		'Default': 'افتراضي',
		'Location': 'الموقع',
		'City:': 'المدينة:',
		'Latitude:': 'خط العرض:',
		'Longitude:': 'خط الطول:',
		'Time Zone:': 'النطاق الزمني:',
		'Location: %s': 'الموقع: %s',
		'Qibla is %.2f° from True North': 'القبلة على بعد %.2f درجة من الشمال الحقيقي',
		'Fajr\t\t\t\t\t%s': 'الفجر\t\t\t\t\t%s',
		'Shuruk\t\t\t%s': 'الشروق\t\t\t\t%s',
		'Dhuhr\t\t\t\t%s': 'الظهر\t\t\t\t\t%s',
		'Asr\t\t\t\t\t%s': 'العصر\t\t\t\t\t%s',
		'Maghrib\t\t\t\t%s': 'المغرب\t\t\t\t\t%s',
		'Isha\t\t\t\t%s': 'العشاء\t\t\t\t\t%s',
		'Next Prayer': 'الصلاة التالية',
		'About': 'حول التطبيق',
		'Settings': 'الإعدادات',
		'Quit': 'خروج',
		'%s until %s': '%s حتى صلاة %s',
		'%s in %s': '%s بعد %s',
		'%s Hours': '%s ساعة',
		'%s Minutes': '%s دقيقة',
		'%s Hours and %s Minutes': '%s ساعة و %s دقيقة',
		'%shr': '%s ساعة',
		'%smin': '%s دقيقة',
		'%shr %smin': '%s ساعة %s دقيقة',
		'GitHub Project Page': 'صفحة المشروع على GitHub',
		'A neat Prayer Time Reminder App.\n Simple and complete so no prayer is missed': 'تطبيق أوقات الصلاة.\n بسيط و شامل حتى لا تفوتك أي صلاة',
		'Copyright © %s Silaty Team': 'حقوق النشر © %s فريق صلاتي',
		'Silaty needs to be restarted, restart now?': 'يحتاج التطبيق إلى إعادة تشغيل، إعادة التشغيل الآن؟',
		'Hijri:': 'هجري:',
		'Sunday': 'الأحد',
		'Monday': 'الإثنين',
		'Tuesday': 'الثلاثاء',
		'Wednesday': 'الأربعاء',
		'Thursday': 'الخميس',
		'Friday': 'الجمعة',
		'Saturday': 'السبت',
		'SundayShort': 'ح',
		'MondayShort': 'ن',
		'TuesdayShort': 'ث',
		'WednesdayShort': 'ر',
		'ThursdayShort': 'خ',
		'FridayShort': 'ج',
		'SaturdayShort': 'س',
		'January': 'يناير',
		'February': 'فبراير',
		'March': 'مارس',
		'April': 'أبريل',
		'May': 'مايو',
		'June': 'يونيو',
		'July': 'يوليو',
		'August': 'أغسطس',
		'September': 'سبتمبر',
		'October': 'أكتوبر',
		'November': 'نوفمبر',
		'December': 'ديسمبر',
		'Muharram': 'محرم',
		'Safar': 'صفر',
		'Rabi al Awwal': 'ربيع الأول',
		'Rabi al Akhira': 'ربيع الآخر',
		'Jumada al Ula': 'جمادى الأولى',
		'Jumada al Akhira': 'جمادى الآخرة',
		'Rajab': 'رجب',
		'Sha\'ban': 'شعبان',
		'Ramadhan': 'رمضان',
		'Shawwal': 'شوال',
		'Dhu al Qa\'da': 'ذو القعدة',
		'Dhu al Hijja': 'ذو الحجة',
		'Qibla direction :': 'اتجاه القبلة :',
		'Country : %s': 'الدولة : %s',
		'City : %s': 'المدينة : %s',
		'Search:': 'بحث:',
		'Check your location on %s': 'يمكنك التحقق من موقعك على %s',
		'Get Ready': 'إستعد',
		'%s minutes left until the %s prayer.': '%s دقائق متبقية حتى صلاة %s.',
		'Prayer time for %s': 'وقت صلاة %s',
		'It\'s time for the %s prayer.': 'حان الوقت لصلاة %s.',
		'%s, %s': '%s، %s',
		'%s - %s, %s / %s': '%s - %s، %s / %s',
		'AM': 'ص',
		'PM': 'م',
		'Apply': 'ضبط',
		'Cancel': 'إلغاء',
	}
	frenchTranslations = {
		'Silaty': 'Silaty',
		'Fajr': 'Fajr',
		'Shuruk': 'Lever du Soleil',
		'Dhuhr': 'Dhuhr',
		'Asr': 'Asr',
		'Maghrib': 'Maghrib',
		'Isha': 'Isha',
		'System': 'Système',
		'Start Minimized:': "Lancer l'application minimisée",
		'Daylight Saving Time:': "Heure d'été:",
		'Clock Format:': "Format de l'heure",
		'12h': '12 heures',
		'24h': '24 heures',
		'Adjust Hijri Calendar:': 'Ajuster le calendrier Hijri',
		'Language:': 'Langue:',
		'English': 'Anglais',
		'French': 'Français',
		'Arabic': 'Arabe',
		'Spanish': 'Espagnol'
		'Notifications': 'Notifications',
		'Show Time left with Icon:': 'Montrer temps restant avec icone:',
		'Enable audio notifications:': 'Activer les notifications audio:',
		'Time before notification:': 'Temps avant la notification:',
		'Fajr Adhan:': 'Adhan de Fajr:',
		'Normal Adhan:': 'Adhan normal:',
		'Jurisprudence': 'Jurisprudence',
		'Calculation Method:': 'Methode de Calcul:',
		'Makkah': 'Makkah',
		'Egypt': 'Egypte',
		'Karachi': 'Karachi',
		'ISNA': 'ISNA (Amérique du Nord)',
		'MWL': 'Ligue Musulmane Mondiale',
		'Madhab:': 'Madhab:',
		'Hanafi': 'Hanafi',
		'Default': 'Défaut',
		'Location': 'Location',
		'City:': 'Ville:',
		'Latitude:': 'Latitude:',
		'Longitude:': 'Longitude:',
		'Time Zone:': 'Fuseau Horaire:',
		'Location: %s': 'Location: %s',
		'Qibla is %.2f° from True North': 'La Qibla est à %.2f du vrai Nord',
		'Fajr\t\t\t\t\t%s': 'Fajr\t\t\t\t\t%s',
		'Shuruk\t\t\t%s': 'Lever du Soleil\t\t\t\t%s',
		'Dhuhr\t\t\t\t%s': 'Dhurh\t\t\t\t\t%s',
		'Asr\t\t\t\t\t%s': 'Asr\t\t\t\t\t%s',
		'Maghrib\t\t\t\t%s': 'Maghrib\t\t\t\t\t%s',
		'Isha\t\t\t\t%s': 'Isha\t\t\t\t\t%s',
		'Next Prayer': 'Prochaine Prière:',
		'About': 'À propos',
		'Settings': 'Options',
		'Quit': 'Quitter',
		'%s until %s': '%s avant %s',
		'%s in %s': '%s dans %s',
		'%s Hours': '%s Heures',
		'%s Minutes': '%s Minutes',
		'%s Hours and %s Minutes': '%s Heures et %s Minutes',
		'%shr': '%sheures',
		'%smin': '%smin',
		'%shr %smin': '%sheures %smin',
		'GitHub Project Page': 'Page GitHub du Projet',
		'A neat Prayer Time Reminder App.\n Simple and complete so no prayer is missed': "Une application polie de rappel pour le temps de Prièr.\n Simple et complète pour qu'aucune prière ne soit ratée",
		'Copyright © %s Silaty Team': 'Copyright © %s Silaty Team',
		'Silaty needs to be restarted, restart now?': "Silaty a besoin d'être redémarrée, redémarrer maintenent ?",
		'Hijri:': 'Hijri:',
		'Sunday': 'Dimanche',
		'Monday': 'Lundi',
		'Tuesday': 'Mardi',
		'Wednesday': 'Mercredi',
		'Thursday': 'Jeudi',
		'Friday': 'Vendredi',
		'Saturday': 'Saturday',
		'SundayShort': 'D',
		'MondayShort': 'L',
		'TuesdayShort': 'Ma',
		'WednesdayShort': 'Me',
		'ThursdayShort': 'J',
		'FridayShort': 'V',
		'SaturdayShort': 'S',
		'January': 'Janvier',
		'February': 'Février',
		'March': 'Mars',
		'April': 'Avril',
		'May': 'Mai',
		'June': 'Juin',
		'July': 'Juillet',
		'August': 'Aôut',
		'September': 'Septembre',
		'October': 'Octobre',
		'November': 'Novembre',
		'December': 'Decembre',
		'Muharram': 'Muharram',
		'Safar': 'Safar',
		'Rabi al Awwal': 'Rabi al Awwal',
		'Rabi al Akhira': 'Rabi al Akhira',
		'Jumada al Ula': 'Jumada al Ula',
		'Jumada al Akhira': 'Jumada al Akhira',
		'Rajab': 'Rajab',
		'Sha\'ban': 'Sha\'ban',
		'Ramadhan': 'Ramadhan',
		'Shawwal': 'Shawwal',
		'Dhu al Qa\'da': 'Dhu al Qa\'da',
		'Dhu al Hijja': 'Dhu al Hijja',
		'Qibla direction :': 'Direction de la Qibla :',
		'Country : %s': 'Pays : %s',
		'City : %s': 'Ville : %s',
		'Search:': 'Chercher:',
		'Check your location on %s': 'Vérifiez votre location sur %s',
		'Get Ready': 'Préparez-vous',
		'%s minutes left until the %s prayer.': '%s minutes avant la prière de %s.',
		'Prayer time for %s': 'Temps de prière pour %s',
		'It\'s time for the %s prayer.': "C'est le temps pour la prière de %s.",
		'%s, %s': '%s، %s',
		'%s - %s, %s / %s': '%s - %s، %s / %s',
		'AM': 'AM', #The correct should be Avant midi and Après midi, but it's too long.
		'PM': 'PM',
		'Apply': 'Appliquer',
		'Cancel': 'Annuler',
	}
	spanishTranslations = {
		'Silaty': 'Silaty',
		'Fajr': 'Fajr',
		'Shuruk': 'Amanecer',
		'Dhuhr': 'Dhuhr',
		'Asr': 'Asr',
		'Maghrib': 'Maghrib',
		'Isha': 'Isha',
		'System': 'Systema',
		'Start Minimized:': "Inicial Minimizado:",
		'Daylight Saving Time:': "Horario de verano:",
		'Clock Format:': "Formato de reloj:",
		'12h': '12 horas',
		'24h': '24 horas',
		'Adjust Hijri Calendar:': 'Ajustar el Calendario Hijri:',
		'Language:': 'Idioma:',
		'English': 'Ingles',
		'French': 'Frances',
		'Arabic': 'Arabe',
		'Spanish': 'Español'
		'Notifications': 'Notificaciones',
		'Show Time left with Icon:': 'Monstrar tiempo restante con icono:',
		'Enable audio notifications:': 'Activar las notificaciones audio:',
		'Time before notification:': 'Tiempo antes de la notificacion:',
		'Fajr Adhan:': 'Adhan de Fajr:',
		'Normal Adhan:': 'Adhan normal:',
		'Jurisprudence': 'Jurisprudencia',
		'Calculation Method:': 'Método de cálculo:',
		'Makkah': 'Meca',
		'Egypt': 'Egipto',
		'Karachi': 'Karachi',
		'ISNA': 'ISNA (Norteamérica)',
		'MWL': 'Liga Mundial Musulmana',
		'Madhab:': 'Madhab:',
		'Hanafi': 'Hanafi',
		'Default': 'Defecto',
		'Location': 'Locacion',
		'City:': 'Ciudad:',
		'Latitude:': 'Latitud:',
		'Longitude:': 'Longitud:',
		'Time Zone:': 'Zona horaria:',
		'Location: %s': 'Locacion: %s',
		'Qibla is %.2f° from True North': 'La Qibla esta a %.2f del verdadero Norte',
		'Fajr\t\t\t\t\t%s': 'Fajr\t\t\t\t\t%s',
		'Shuruk\t\t\t%s': 'Amanecer\t\t\t\t%s',
		'Dhuhr\t\t\t\t%s': 'Dhurh\t\t\t\t\t%s',
		'Asr\t\t\t\t\t%s': 'Asr\t\t\t\t\t%s',
		'Maghrib\t\t\t\t%s': 'Maghrib\t\t\t\t\t%s',
		'Isha\t\t\t\t%s': 'Isha\t\t\t\t\t%s',
		'Next Prayer': 'Proximo rezo:',
		'About': 'À propos',
		'Settings': 'Acerca de',
		'Quit': 'Quitar',
		'%s until %s': '%s antes de %s',
		'%s in %s': '%s en %s',
		'%s Hours': '%s Horas',
		'%s Minutes': '%s Minutos',
		'%s Hours and %s Minutes': '%s Heros et %s Minutos',
		'%shr': '%shoras',
		'%smin': '%smin',
		'%shr %smin': '%shoras %smin',
		'GitHub Project Page': 'Pagina GitHub del Proyecto',
		'A neat Prayer Time Reminder App.\n Simple and complete so no prayer is missed': "Una excelente aplicación para los tiempos de oracion.\n Simple y completa para que no se olvide ninguna oración",
		'Copyright © %s Silaty Team': 'Copyright © %s Silaty Team',
		'Silaty needs to be restarted, restart now?': "Silaty necesita ser reiniciado, ¿reiniciar ahora?",
		'Hijri:': 'Hijri:',
		'Sunday': 'Domindo',
		'Monday': 'Lunes',
		'Tuesday': 'Martes',
		'Wednesday': 'Miercoles',
		'Thursday': 'Jueves',
		'Friday': 'Viernes',
		'Saturday': 'Sabado',
		'SundayShort': 'D',
		'MondayShort': 'L',
		'TuesdayShort': 'Ma',
		'WednesdayShort': 'Mi',
		'ThursdayShort': 'J',
		'FridayShort': 'V',
		'SaturdayShort': 'S',
		'January': 'Enero',
		'February': 'Febrero',
		'March': 'Marzo',
		'April': 'April',
		'May': 'mayo',
		'June': 'Junio',
		'July': 'Julio',
		'August': 'Agosto',
		'September': 'Septiembre',
		'October': 'Octubre',
		'November': 'Noviembre',
		'December': 'Diciembre',
		'Muharram': 'Muharram',
		'Safar': 'Safar',
		'Rabi al Awwal': 'Rabi al Awwal',
		'Rabi al Akhira': 'Rabi al Akhira',
		'Jumada al Ula': 'Jumada al Ula',
		'Jumada al Akhira': 'Jumada al Akhira',
		'Rajab': 'Rajab',
		'Sha\'ban': 'Sha\'ban',
		'Ramadhan': 'Ramadhan',
		'Shawwal': 'Shawwal',
		'Dhu al Qa\'da': 'Dhu al Qa\'da',
		'Dhu al Hijja': 'Dhu al Hijja',
		'Qibla direction :': 'Direccion de la Qibla :',
		'Country : %s': 'País : %s',
		'City : %s': 'Ciudad : %s',
		'Search:': 'Burcar:',
		'Check your location on %s': 'Consulta tu ubicación sobre %s',
		'Get Ready': 'Prepararse',
		'%s minutes left until the %s prayer.': '%s minutos antes de la oracion de %s.',
		'Prayer time for %s': 'Hora de la oracian para %s',
		'It\'s time for the %s prayer.': "Es la hora de la oracion %s.",
		'%s, %s': '%s، %s',
		'%s - %s, %s / %s': '%s - %s، %s / %s',
		'AM': 'AM',
		'PM': 'PM',
		'Apply': 'Aplicar',
		'Cancel': 'Cancelar',
	}
	englishWeekDays = {
		'SundayShort': 'S',
		'MondayShort': 'M',
		'TuesdayShort': 'T',
		'WednesdayShort': 'W',
		'ThursdayShort': 'T',
		'FridayShort': 'F',
		'SaturdayShort': 'S',
	}

	if language == 'Arabic' and text in arabicTranslations:
		return arabicTranslations[text]
	elif language == 'French' and text in frenchTranslations:
		return frenchTranslations[text]
	elif text in englishWeekDays:
		return englishWeekDays[text]
	else:
		return text
